CREATE TABLE users (username VARCHAR(40) NOT NULL, password VARCHAR(100) NOT NULL, PRIMARY KEY (username));

CREATE TABLE chat_manager (id INT AUTO_INCREMENT NOT NULL, message_key VARCHAR(128) NOT NULL, PRIMARY KEY (id));

CREATE TABLE chat_groups (chat_id INT NOT NULL, name VARCHAR(40) NOT NULL,
FOREIGN KEY (chat_id) REFERENCES chat_manager(id) ON DELETE CASCADE);

CREATE TABLE chat_users (chat_id INT NOT NULL, username VARCHAR(40) NOT NULL,
FOREIGN KEY (chat_id) REFERENCES chat_manager(id) ON DELETE CASCADE,
FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE chats (msg_id INT AUTO_INCREMENT NOT NULL, chat_id INT NOT NULL, sender VARCHAR(40) NOT NULL, message TEXT NOT NULL, time DATETIME NOT NULL,
PRIMARY KEY (msg_id),
FOREIGN KEY (chat_id) REFERENCES chat_manager(id) ON DELETE CASCADE,
FOREIGN KEY (sender) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE);